# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 8) do

  create_table "categories", :force => true do |t|
    t.column "name",        :string
    t.column "description", :string
  end

  create_table "posts", :force => true do |t|
    t.column "category_id",    :integer
    t.column "user_id",        :integer
    t.column "subject",        :string,   :default => "",   :null => false
    t.column "body",           :text
    t.column "view_times",     :integer,  :default => 0
    t.column "if_top",         :boolean
    t.column "if_could_reply", :boolean,  :default => true
    t.column "root_id",        :integer,  :default => 0,    :null => false
    t.column "parent_id",      :integer,  :default => 0,    :null => false
    t.column "lft",            :integer,  :default => 0,    :null => false
    t.column "rgt",            :integer,  :default => 0,    :null => false
    t.column "depth",          :integer,  :default => 0,    :null => false
    t.column "created_at",     :datetime,                   :null => false
    t.column "updated_at",     :datetime,                   :null => false
  end

  create_table "roles", :force => true do |t|
    t.column "role_name", :string
  end

  create_table "special_posts", :force => true do |t|
    t.column "post_id", :integer, :null => false
    t.column "special", :string
    t.column "user_id", :integer, :null => false
  end

  create_table "users", :force => true do |t|
    t.column "username",         :string,   :limit => 50, :default => "",   :null => false
    t.column "password",         :string,                 :default => "",   :null => false
    t.column "role_id",          :integer,                :default => 2,    :null => false
    t.column "lastest_post",     :date
    t.column "created_at",       :datetime,                                 :null => false
    t.column "updated_at",       :datetime,                                 :null => false
    t.column "email",            :string
    t.column "QQ",               :string
    t.column "if_active",        :boolean,                :default => true, :null => false
    t.column "password_confirm", :string
    t.column "lastest_login",    :datetime
  end

end
